export const DENY_ALL_INGRESS = 'DENY_ALL_INGRESS'
export const DENY_ALL_EGRESS = 'DENY_ALL_EGRESS'
export const ALLOW_ALL_INGRESS = 'ALLOW_ALL_INGRESS'
export const ALLOW_ALL_EGRESS = 'ALLOW_ALL_EGRESS'
